apiVersion: v1
kind: Pod
metadata:
  name: kube-proxy
  namespace: kube-system
spec:
  containers:
  - name: kube-proxy
    image: k8s.gcr.io/kube-proxy:v1.22.0
    command:
    - "/usr/local/bin/kube-proxy"
    securityContext:
      privileged: true
    volumeMounts:
    - name: kube-proxy-config
      mountPath: /etc/kubernetes/config.conf
      readOnly: true
  volumes:
  - name: kube-proxy-config
    configMap:
      name: kube-proxy-config
