apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  volumes:
  - name: shared-volume
    hostPath:
      path: /var/lib/data
  containers:
  - name: container1
    image: nginx
    ports:
    - containerPort: 8080
    resources:
      limits:
        cpu: "500m"
        memory: "256Mi"
    volumeMounts:
    - name: shared-volume
      mountPath: /data
  - name: container2
    image: nginx
    ports:
    - containerPort: 8081
    resources:
      limits:
        cpu: "500m"
        memory: "256Mi"
    volumeMounts:
    - name: shared-volume
      mountPath: /data
  - name: container3
    image: nginx
    ports:
    - containerPort: 8082
    resources:
      limits:
        cpu: "500m"
        memory: "256Mi"
    volumeMounts:
    - name: shared-volume
      mountPath: /data
