apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: my-container
    image: nginx:latest
    volumeMounts:
    - name: cache-volume
      mountPath: /cache
    - name: data-volume
      mountPath: /data
  volumes:
  - name: cache-volume
    emptyDir: {}
  - name: data-volume
    persistentVolumeClaim:
      claimName: my-pvc
