apiVersion: v1
kind: ConfigMap
metadata:
  name: dex
  namespace: dex
data:
  config.yaml: |
    issuer: https://dex.example.com
    storage:
      type: memory
    connectors:
    - type: ldap
      id: ldap
      name: LDAP
      config:
        host: ldap.example.com:389
        insecureNoSSL: false
        bindDN: "cn=admin,dc=example,dc=com"
        bindPW: "admin-password"
        userSearch:
          baseDN: "dc=example,dc=com"
          filter: "(objectClass=person)"
          username: sAMAccountName
          idAttr: uid
          emailAttr: mail
          nameAttr: cn
