apiVersion: v1
kind: Pod
metadata:
  name: my-app
spec:
  containers:
  - name: my-container
    image: nginx
    env:
    - name: DATABASE_URL
      valueFrom:
        configMapKeyRef:
          name: my-config
          key: DATABASE_URL
    - name: APP_ENV
      valueFrom:
        configMapKeyRef:
          name: my-config
          key: APP_ENV
    volumeMounts:
    - name: config-volume
      mountPath: "/etc/nginx/conf.d"
  volumes:
  - name: config-volume
    configMap:
      name: my-config
      items:
      - key: custom.conf
        path: custom.conf
