name: Simple Action on Pull Request

on:
  issue_comment:
    types: [created]
  pull_request:
    types: [closed]

jobs:
  run_if:
    if: contains(github.event.comment.body, '/deploy')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Print message
        run: echo "PR comment triggered me"
