name: Simple Action on Master Push

on:
  push:
    branches:
      - master

jobs:
  simple-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Print message
        run: echo "Hello, world! This action ran on a push to the master branch!"
